set( PROJECT_SOURCES

        src/adc.c
        src/bluetooth.c
        src/button.c
        src/error.c
        src/ErrorState.c
        src/ESP8266.c
        src/events.c
        src/fsm_evt_queue.c
        src/InitState.c
        src/main.c
        src/microphone.c
        src/server.c
        src/SPH0645.c
        src/stm32l4xx_hal_msp.c
        src/state_machine.c
        src/stm32l4xx_it.c
        #src/syscalls.c
        src/system_stm32l4xx.c
        src/TestState.c


        HAL_Driver/src/stm32l4xx_hal_rcc.c
        HAL_Driver/src/stm32l4xx_ll_rtc.c
        HAL_Driver/src/stm32l4xx_hal_smartcard.c
        HAL_Driver/src/stm32l4xx_ll_dma2d.c
        HAL_Driver/src/stm32l4xx_ll_tim.c
        HAL_Driver/src/stm32l4xx_ll_spi.c
        HAL_Driver/src/stm32l4xx_ll_usb.c
        HAL_Driver/src/stm32l4xx_hal_lptim.c
        # HAL_Driver/src/stm32l4xx_hal_timebase_tim_template.c
        HAL_Driver/src/stm32l4xx_ll_opamp.c
        HAL_Driver/src/stm32l4xx_hal_nand.c
        HAL_Driver/src/stm32l4xx_ll_fmc.c
        HAL_Driver/src/stm32l4xx_hal_opamp_ex.c
        HAL_Driver/src/stm32l4xx_hal_i2c_ex.c
        HAL_Driver/src/stm32l4xx_hal_dfsdm_ex.c
        HAL_Driver/src/stm32l4xx_hal_pcd_ex.c
        HAL_Driver/src/stm32l4xx_hal_usart_ex.c
        HAL_Driver/src/stm32l4xx_hal_tim_ex.c
        HAL_Driver/src/stm32l4xx_ll_exti.c
        HAL_Driver/src/stm32l4xx_hal_smbus.c
        HAL_Driver/src/stm32l4xx_hal_i2c.c
        HAL_Driver/src/stm32l4xx_hal_wwdg.c
        HAL_Driver/src/stm32l4xx_hal_exti.c
        HAL_Driver/src/stm32l4xx_hal_nor.c
        HAL_Driver/src/stm32l4xx_ll_crs.c
        HAL_Driver/src/stm32l4xx_hal_uart_ex.c
        HAL_Driver/src/stm32l4xx_hal_swpmi.c
        HAL_Driver/src/stm32l4xx_hal_pcd.c
        HAL_Driver/src/stm32l4xx_hal_iwdg.c
        HAL_Driver/src/stm32l4xx_hal_dac_ex.c
        HAL_Driver/src/stm32l4xx_hal_uart.c
        HAL_Driver/src/stm32l4xx_hal_crc_ex.c
        HAL_Driver/src/stm32l4xx_hal_sd_ex.c
        HAL_Driver/src/stm32l4xx_ll_i2c.c
        HAL_Driver/src/stm32l4xx_hal_ltdc_ex.c
        HAL_Driver/src/stm32l4xx_ll_utils.c
        HAL_Driver/src/stm32l4xx_hal_flash.c
        HAL_Driver/src/stm32l4xx_ll_usart.c
        HAL_Driver/src/stm32l4xx_hal_smartcard_ex.c
        HAL_Driver/src/Legacy
        HAL_Driver/src/stm32l4xx_hal_rtc.c
        HAL_Driver/src/stm32l4xx_hal_rcc_ex.c
        HAL_Driver/src/stm32l4xx_ll_rcc.c
        HAL_Driver/src/stm32l4xx_hal_sd.c
        HAL_Driver/src/stm32l4xx_hal_spi.c
        HAL_Driver/src/stm32l4xx_hal_spi_ex.c
        HAL_Driver/src/stm32l4xx_hal_dma_ex.c
        HAL_Driver/src/stm32l4xx_hal_cortex.c
        HAL_Driver/src/stm32l4xx_hal_pwr_ex.c
        HAL_Driver/src/stm32l4xx_ll_sdmmc.c
        HAL_Driver/src/stm32l4xx_hal_tim.c
        HAL_Driver/src/stm32l4xx_hal_dfsdm.c
        HAL_Driver/src/stm32l4xx_hal_firewall.c
        HAL_Driver/src/stm32l4xx_hal_gpio.c
        HAL_Driver/src/stm32l4xx_ll_gpio.c
        HAL_Driver/src/stm32l4xx_hal_crc.c
        HAL_Driver/src/stm32l4xx_hal_hash_ex.c
        HAL_Driver/src/stm32l4xx_hal_dsi.c
        HAL_Driver/src/stm32l4xx_hal_opamp.c
        HAL_Driver/src/stm32l4xx_hal_rtc_ex.c
        HAL_Driver/src/stm32l4xx_ll_lptim.c
        HAL_Driver/src/stm32l4xx_hal_lcd.c
        HAL_Driver/src/stm32l4xx_ll_pwr.c
        HAL_Driver/src/stm32l4xx_hal_can.c
        HAL_Driver/src/stm32l4xx_ll_adc.c
        HAL_Driver/src/stm32l4xx_hal_rng.c
        HAL_Driver/src/stm32l4xx_hal_hcd.c
        HAL_Driver/src/stm32l4xx_hal_sai_ex.c
        HAL_Driver/src/stm32l4xx_hal_sram.c
        HAL_Driver/src/stm32l4xx_ll_dac.c
        HAL_Driver/src/stm32l4xx_ll_comp.c
        HAL_Driver/src/stm32l4xx_hal_ospi.c
        HAL_Driver/src/stm32l4xx_ll_dma.c
        HAL_Driver/src/stm32l4xx_hal_tsc.c
        HAL_Driver/src/stm32l4xx_hal_dma2d.c
        HAL_Driver/src/stm32l4xx_hal_comp.c
        HAL_Driver/src/stm32l4xx_ll_rng.c
        HAL_Driver/src/stm32l4xx_hal_qspi.c
        HAL_Driver/src/stm32l4xx_hal_dcmi.c
        HAL_Driver/src/stm32l4xx_hal_flash_ramfunc.c
        HAL_Driver/src/stm32l4xx_hal_cryp_ex.c
        HAL_Driver/src/stm32l4xx_hal_hash.c
        HAL_Driver/src/stm32l4xx_hal_adc.c
        HAL_Driver/src/stm32l4xx_hal_adc_ex.c
        HAL_Driver/src/stm32l4xx_hal_flash_ex.c
        HAL_Driver/src/stm32l4xx_hal_dma.c
        HAL_Driver/src/stm32l4xx_hal_usart.c
        HAL_Driver/src/stm32l4xx_hal_sai.c
        HAL_Driver/src/stm32l4xx_ll_lpuart.c
        HAL_Driver/src/stm32l4xx_hal.c
        HAL_Driver/src/stm32l4xx_hal_dac.c
        HAL_Driver/src/stm32l4xx_hal_cryp.c
        HAL_Driver/src/stm32l4xx_ll_crc.c
        HAL_Driver/src/stm32l4xx_hal_ltdc.c
        HAL_Driver/src/stm32l4xx_hal_irda.c
        HAL_Driver/src/stm32l4xx_hal_gfxmmu.c
        HAL_Driver/src/stm32l4xx_ll_swpmi.c
        HAL_Driver/src/stm32l4xx_hal_pwr.c

        Utilities/STM32L4xx_Nucleo_144/stm32l4xx_nucleo_144.c

        inc/adc.h
        inc/bluetooth.h
        inc/button.h
        inc/common.h
        inc/error.h
        inc/ErrorState.h
        inc/ESP8266.h
        inc/events.h
        inc/fsm_evt_queue.h
        inc/InitState.h
        inc/main.h
        inc/microphone.h
        inc/server.h
        inc/SPH0645.h
        inc/state_machine.h
        inc/stm32l4xx_hal_conf.h
        inc/stm32l4xx_it.h
        inc/stm32_assert.h
        inc/TestState.h

        HAL_Driver/inc/stm32l4xx_ll_pwr.h
        HAL_Driver/inc/stm32l4xx_hal_opamp.h
        HAL_Driver/inc/stm32l4xx_hal_dsi.h
        HAL_Driver/inc/stm32l4xx_hal_lcd.h
        HAL_Driver/inc/stm32l4xx_ll_lptim.h
        HAL_Driver/inc/stm32l4xx_hal_rtc_ex.h
        HAL_Driver/inc/stm32l4xx_hal_crc.h
        HAL_Driver/inc/stm32l4xx_ll_gpio.h
        HAL_Driver/inc/stm32l4xx_hal_hash_ex.h
        HAL_Driver/inc/stm32l4xx_hal_dfsdm.h
        HAL_Driver/inc/stm32l4xx_hal_gpio.h
        HAL_Driver/inc/stm32l4xx_hal_firewall.h
        HAL_Driver/inc/stm32l4xx_hal_dma2d.h
        HAL_Driver/inc/stm32l4xx_hal_tsc.h
        HAL_Driver/inc/stm32l4xx_ll_dma.h
        HAL_Driver/inc/stm32l4xx_hal_comp.h
        HAL_Driver/inc/stm32l4xx_ll_bus.h
        HAL_Driver/inc/stm32l4xx_ll_comp.h
        HAL_Driver/inc/stm32l4xx_ll_dac.h
        HAL_Driver/inc/stm32l4xx_hal_sram.h
        HAL_Driver/inc/stm32l4xx_hal_ospi.h
        HAL_Driver/inc/stm32l4xx_hal_hcd.h
        HAL_Driver/inc/stm32l4xx_hal_rng.h
        HAL_Driver/inc/stm32l4xx_hal_sai_ex.h
        HAL_Driver/inc/stm32l4xx_ll_adc.h
        HAL_Driver/inc/stm32l4xx_hal_can.h
        HAL_Driver/inc/stm32l4xx_hal.h
        HAL_Driver/inc/stm32l4xx_ll_lpuart.h
        HAL_Driver/inc/stm32l4xx_hal_sai.h
        HAL_Driver/inc/stm32l4xx_hal_dac.h
        HAL_Driver/inc/stm32l4xx_hal_flash_ex.h
        HAL_Driver/inc/stm32l4xx_hal_adc_ex.h
        HAL_Driver/inc/stm32l4xx_hal_usart.h
        HAL_Driver/inc/stm32l4xx_hal_dma.h
        HAL_Driver/inc/stm32l4xx_hal_flash_ramfunc.h
        HAL_Driver/inc/stm32l4xx_hal_dcmi.h
        HAL_Driver/inc/stm32l4xx_hal_adc.h
        HAL_Driver/inc/stm32l4xx_hal_cryp_ex.h
        HAL_Driver/inc/stm32l4xx_hal_hash.h
        HAL_Driver/inc/stm32l4xx_hal_qspi.h
        HAL_Driver/inc/stm32l4xx_ll_cortex.h
        HAL_Driver/inc/stm32l4xx_ll_rng.h
        HAL_Driver/inc/Legacy
        HAL_Driver/inc/stm32l4xx_ll_swpmi.h
        HAL_Driver/inc/stm32l4xx_hal_gpio_ex.h
        HAL_Driver/inc/stm32l4xx_hal_pwr.h
        HAL_Driver/inc/stm32l4xx_hal_irda.h
        HAL_Driver/inc/stm32l4xx_hal_gfxmmu.h
        HAL_Driver/inc/stm32l4xx_ll_crc.h
        HAL_Driver/inc/stm32l4xx_hal_ltdc.h
        HAL_Driver/inc/stm32l4xx_hal_cryp.h
        HAL_Driver/inc/stm32l4xx_ll_usb.h
        HAL_Driver/inc/stm32l4xx_ll_spi.h
        HAL_Driver/inc/stm32l4xx_ll_tim.h
        HAL_Driver/inc/stm32l4xx_hal_def.h
        HAL_Driver/inc/stm32l4xx_hal_smartcard.h
        HAL_Driver/inc/stm32l4xx_ll_dma2d.h
        HAL_Driver/inc/stm32l4xx_hal_rcc.h
        HAL_Driver/inc/stm32l4xx_ll_rtc.h
        HAL_Driver/inc/stm32l4xx_hal_nor.h
        HAL_Driver/inc/stm32l4xx_hal_irda_ex.h
        HAL_Driver/inc/stm32l4xx_hal_exti.h
        HAL_Driver/inc/stm32l4xx_hal_i2c.h
        HAL_Driver/inc/stm32l4xx_hal_wwdg.h
        HAL_Driver/inc/stm32l4xx_hal_usart_ex.h
        HAL_Driver/inc/stm32l4xx_hal_pcd_ex.h
        HAL_Driver/inc/stm32l4xx_ll_dmamux.h
        HAL_Driver/inc/stm32l4xx_ll_wwdg.h
        HAL_Driver/inc/stm32l4xx_hal_smbus.h
        HAL_Driver/inc/stm32l4xx_ll_exti.h
        HAL_Driver/inc/stm32l4xx_hal_tim_ex.h
        HAL_Driver/inc/stm32l4xx_hal_opamp_ex.h
        HAL_Driver/inc/stm32l4xx_ll_fmc.h
        HAL_Driver/inc/stm32l4xx_hal_dfsdm_ex.h
        HAL_Driver/inc/stm32l4xx_hal_i2c_ex.h
        HAL_Driver/inc/stm32l4xx_hal_lptim.h
        HAL_Driver/inc/stm32l4xx_hal_nand.h
        HAL_Driver/inc/stm32l4xx_ll_opamp.h
        HAL_Driver/inc/stm32l4xx_ll_utils.h
        HAL_Driver/inc/stm32l4xx_hal_flash.h
        HAL_Driver/inc/stm32l4xx_hal_sd_ex.h
        HAL_Driver/inc/stm32l4xx_hal_ltdc_ex.h
        HAL_Driver/inc/stm32l4xx_ll_i2c.h
        HAL_Driver/inc/stm32l4xx_hal_dac_ex.h
        HAL_Driver/inc/stm32l4xx_hal_iwdg.h
        HAL_Driver/inc/stm32l4xx_ll_system.h
        HAL_Driver/inc/stm32l4xx_hal_pcd.h
        HAL_Driver/inc/stm32l4xx_hal_crc_ex.h
        HAL_Driver/inc/stm32l4xx_hal_uart.h
        HAL_Driver/inc/stm32l4xx_ll_crs.h
        HAL_Driver/inc/stm32l4xx_hal_swpmi.h
        HAL_Driver/inc/stm32l4xx_hal_uart_ex.h
        HAL_Driver/inc/stm32l4xx_ll_iwdg.h
        HAL_Driver/inc/stm32l4xx_ll_sdmmc.h
        HAL_Driver/inc/stm32l4xx_hal_pwr_ex.h
        HAL_Driver/inc/stm32l4xx_hal_cortex.h
        HAL_Driver/inc/stm32l4xx_hal_dma_ex.h
        HAL_Driver/inc/stm32l4xx_hal_tim.h
        HAL_Driver/inc/stm32l4xx_hal_sd.h
        HAL_Driver/inc/stm32l4xx_hal_spi.h
        HAL_Driver/inc/stm32l4xx_hal_spi_ex.h
        HAL_Driver/inc/stm32l4xx_hal_rcc_ex.h
        HAL_Driver/inc/stm32l4xx_hal_rtc.h
        HAL_Driver/inc/stm32l4xx_ll_rcc.h
        HAL_Driver/inc/stm32l4xx_hal_smartcard_ex.h
        HAL_Driver/inc/stm32l4xx_ll_usart.h

        CMSIS/core/core_cm7.h
        CMSIS/core/arm_const_structs.h
        CMSIS/core/core_cm3.h
        CMSIS/core/arm_common_tables.h
        CMSIS/core/cmsis_armcc.h
        CMSIS/core/core_cm4.h
        CMSIS/core/core_cm0.h
        CMSIS/core/arm_math.h
        CMSIS/core/core_cmInstr.h
        CMSIS/core/core_cmFunc.h
        CMSIS/core/core_sc000.h
        CMSIS/core/core_sc300.h
        CMSIS/core/cmsis_gcc.h
        CMSIS/core/cmsis_armcc_V6.h
        CMSIS/core/core_cm0plus.h
        CMSIS/core/core_cmSimd.h

        CMSIS/device/system_stm32l4xx.h
        CMSIS/device/stm32l4r5xx.h
        CMSIS/device/stm32l4xx.h

        Utilities/STM32L4xx_Nucleo_144/stm32l4xx_nucleo_144.h

        startup/startup_stm32l4r5xx.s
)
